<?php
return [
    "deviceconfig" => [
        [
            "devtype"     => 1,
            "devname"     => "大朋E2",
            "url"         => "http://down.vrgame.vronline.com/drives/deepoon_e2.zip",
            "size"        => 18964063,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "大朋E2是上海乐相科技推出的虚拟现实头戴式显示器产品。",
            "version"     => "1.0.0.0",
            "startmode"   => "--mode unattended",
            "regpath"     => "DpnVR",
            "regkey"      => "DPN_RUNTIME_VERSION",
            "processname" => "DPNAssistant_V1.5.0.10.exe",
        ],
        [
            "devtype"     => 2,
            "devname"     => "Oculus DK2",
            "url"         => "http://down.vrgame.vronline.com/drives/oculus_runtime_sdk_0.8.0.0_win.exe",
            "size"        => 46565104,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "Oculus Rift Development Kit2是Oculus推出的面向于VR开发者的虚拟现实头戴式显示器开发套件。",
            "version"     => "0.8.0.0-public-release-117061",
            "startmode"   => "--mode unattended",
            "regpath"     => "Oculus VR, LLC\\Oculus Runtime",
            "regkey"      => "Version",
            "processname" => "oculus_runtime_sdk_0.8.0.0_win.exe",
        ],
        [
            "devtype"     => 3,
            "devname"     => "Oculus CV1",
            "url"         => "http://down.vrgame.vronline.com/drives/OculusSetup_03.zip",
            "size"        => 1607928110,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "Oculus Rift CV1是Oculus推出的虚拟现实头戴式显示器的正式零售版本。",
            "version"     => "1.0.0.2",
            "startmode"   => "",
            "regpath"     => "Oculus VR, LLC\\Oculus",
            "regkey"      => "DriverVersion",
            "processname" => "OculusSetup.zip",
        ],
        [
            "devtype"     => 4,
            "devname"     => "HTC Vive",
            "url"         => "http://down.vrgame.vronline.com/drives/SteamVR_02.zip",
            "size"        => 456258470,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "HTC Vive是由HTC与Valve联合开发的虚拟现实头戴式显示器产品。",
            "version"     => "0.0.0.1",
            "startmode"   => "--mode unattended",
            "regpath"     => "Valve\\Steam",
            "regkey"      => "InstallPath",
            "processname" => "SteamVR/tools/bin/win32/vrmonitor.exe",
        ],
        [
            "devtype"     => 5,
            "devname"     => "OSVR",
            "url"         => "http://down.vrgame.vronline.com/drives/OSVR Runtime Setup.Argand.0.6.1320.1.exe",
            "size"        => 45776016,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "OSVR虚拟现实头戴式显示器产品。",
            "version"     => "0.0.0.1",
            "startmode"   => "/S",
            "regpath"     => "OSVR",
            "regkey"      => "InstalledVersion",
            "processname" => "OSVR Runtime Setup.Argand.0.6.1320.1.exe",
        ],
        [
            "devtype"     => 6,
            "devname"     => "大朋E3",
            "url"         => "http://down.vrgame.vronline.com/drives/Deepoon_E3_05.zip",
            "size"        => 8003266,
            "crc32"       => 0,
            "image"       => "",
            "desc"        => "大朋E3是上海乐相科技推出的虚拟现实头戴式显示器产品。",
            "version"     => "2.0.0.1",
            "startmode"   => "--mode unattended",
            "regpath"     => "DpnVR",
            "processname" => "",
            "regkey"      => "DPN_RUNTIME_VERSION",
        ],
    ],
];
